### PR TITLE
MDS-1195: New analytics tracker

### PR DESCRIPTION
**Pull request by ActionAnalytics**

### CODE REVIEW

**Comment by ActionAnalytics** [comment]
Hi @mmumby can I get this reviewed pls?

**Comment by FreshGyan** [comment]
Seems like there are CORS issues on the script:
https://mds-empr-mds-dev.pathfinder.gov.bc.ca/429/

**Comment by ActionAnalytics** [comment]
Can you provide more info Gyan?  How would you explain this to Jill and how would you recommend going forward with implementing this then?

**Comment by mmumby** [comment]
@ActionAnalytics Refactoring the script will likely take as long as creating a Jira ticket.

Again, this was just a suggestion to make the implementation cleaner, either address it in this PR or leave the code as is. No need to bloat the backlog for this.

**Comment by ActionAnalytics** [comment]
@mmumby want to do it for me?  The change is quick yes, but for me the context switch between projects isn't, along with testing that it works.  If you have cycles I would genuinely appreciate this as I'm working on several other things at the moment.

**Comment by FreshGyan** [comment]
Hey guys!
So maybe a miscommunication here. The application doesn't break the app.
But due to a different origin JS call, the browser kills any requests going out from the application.
I simply visited the URL and looked at the network tab to observe what a regular HTTP request looks like for snowplow to plow our app and all i saw was:
image

**Comment by ActionAnalytics** [comment]
Thanks I'll follow up on that and update us here.

**Comment by FreshGyan** [comment]
Talked with Julian and closing for now. But can be resurrected later.

**Pull request closed without merging**
