### PR TITLE
[MDS-5254] Now discrepancy VFCBC vs Core - UNDRIP

### PR DESCRIPTION
**Pull request by isuru-aot**
## Objective 

[MDS-5254](https://bcmines.atlassian.net/browse/MDS-5254)

_Why are you making this change? Provide a short explanation and/or screenshots_

- Added new field `has_acknowledged_undrip` in core API (`now-submissions/applications`) matching to `hasacknowledgedundrip` field in VFCBC. 
- Added `Indigenous Engagement` section in core view to show the `has_acknowledged_undrip`  value.
- Remove the `cultural-heritage-resources` section in core view.

mds-5254-3

### CODE REVIEW

**Review by henryoforeh-dev — DISMISSED** [review]
Nice!

**Review by taraepp — DISMISSED** [review]
👍

**Review by simensma-fresh — DISMISSED** [review]
Looks good! Maybe let's hold off on merging this until we've deployed things to prod

**Review by henryoforeh-dev — APPROVED** [review]

**Review by matbusby-fw — APPROVED** [review]
Looks great!  Nice work Isuru!  Let's wait to merge it until we complete the push to prod though!

**Comment by simensma-fresh** [comment]
@isuru-aot  Should be good to merge this in :)

**Pull request merged**
