### PR TITLE
[MDS-6139] project stages application button

### PR DESCRIPTION
**Pull request by taraepp**
## Objective 
- make the application "start" button work on MS
- also fixed some "duplicate key" warnings and made things TS-y
- I didn't see the same issue on CORE but made that TS-y too.
- fixed the route for the app-help work on those pages too

[MDS-6139](https://bcmines.atlassian.net/browse/MDS-6139)

_Why are you making this change? Provide a short explanation and/or screenshots_

### CODE REVIEW

**Review by matbusby-fw — DISMISSED** [review]
Everything looks good to me.  Sonarcloud is pointing out a valid issue that I know didn't have anything to do with your code, but should be a pretty easy fix:

```
label =
            record.key && record.stage_status
              ? `[${record.stage_status_hash[text]}]` || "N/A"
              : "[Not submitted]";
```

Since it's interpolating the string and using `[]` it is always going to be truthy.  Might be worth fixing this here?

**Review by matbusby-fw — DISMISSED** [review]
🦙

**Review by matbusby-fw — APPROVED** [review]
🐫

**Comment by henry-ngo** [comment]
maybe wrong tag for me? :)

**Review by simensma-fresh — APPROVED** [review]

**Review by henryoforeh-dev — APPROVED** [review]

**Pull request merged**
