### PR TITLE
[MDS-5098] More Accurate Arch Diagram - v2

### PR DESCRIPTION
**Pull request by vyasworks**
## Objective 

[MDS-5098](https://bcmines.atlassian.net/browse/MDS-5098)

### CODE REVIEW

**Review by taraepp — COMMENTED** [review]
I just have a question about what the "S" means on the deployments (ex: "S: mds")

**Comment by vyasworks** [comment]
> I just have a question about what the "S" means on the deployments (ex: "S: mds")

S: is schema that this particular deployment uses. This is symbolized with the db connection icon.

**Comment by taraepp** [comment]
> 

I think the icon didn't get included, I only see something like that for the redis cache:
image

**Comment by vyasworks** [comment]
> > 
> 
> I think the icon didn't get included, I only see something like that for the redis cache: image

They are included, git's rich diff seems to be having troubles doing the rendering. 

Try downloading the svg or can refer this : 

https://apps.nrs.gov.bc.ca/int/confluence/download/attachments/42107578/MDS_Arch-Arch-V2.jpg?version=1&modificationDate=1679437013000&api=v2

**Review by simensma-fresh — APPROVED** [review]

**Review by taraepp — APPROVED** [review]

**Pull request merged**
