### PR TITLE
MDS-3242: Admins Can Edit Proposed Start & Authorization End Dates and Proposed Annual Maximum Tonnage + More

### PR DESCRIPTION
**Pull request by exzizt**
# Main
* Admins can update the Proposed Start Date, Proposed End Date, and Proposed Annual Maximum Tonnage under the Application tab
image

* Renames Proposed End Date to Proposed Authorization End Date (and renames this in the generatable Edited Application document as well)
image

* Applies the correct validation when setting the Authorization End Date (when issuing a permit) for placer applications

# Other
* Removes the length specification on `response_url` for `now_application_review`
* Properly sets the loading/submitting state for some buttons
* Fixes a possible "index out of range" error for the permittee name hybrid property
* Minor text changes

### CODE REVIEW

**Comment by exzizt** [comment]
No idea why one front-end test is failing... It works in the actual app.

image

**Comment by exzizt** [comment]
Feel free to make any necessary changes and merge it in if I can't resolve things before I start my holidays.

**Comment by mmumby** [comment]
> No idea why one front-end test is failing... It works in the actual app.
> 
> image

Is this still failing?

**Comment by exzizt** [comment]
> > No idea why one front-end test is failing... It works in the actual app.
> > image
> 
> Is this still failing?

Nope

**Review by mhuseinov — APPROVED** [review]

**Pull request merged**
