### PR TITLE
[MDS-5343] adjusting permit enclosed letter doc

### PR DESCRIPTION
**Pull request by asinn134**
## Objective 

-  Missing change to the Permit Enclosed Letter document template.

[MDS-5343](https://bcmines.atlassian.net/browse/MDS-5343)

image

How the permit enclosed document looks:

image

### CODE REVIEW

**Review by henryoforeh-dev — DISMISSED** [review]

**Comment by taraepp** [comment]
I've noticed that this form allows you to edit the letter body. Are these changes compatible with that?
image

**Comment by asinn134** [comment]
> I've noticed that this form allows you to edit the letter body. Are these changes compatible with that? image
@taraepp, hmmm good point, in this case having the text in the document won't really work.

**Comment by asinn134** [comment]
@taraepp I ended up changing the permit enclosed word document back to how it was originally, and moved the update to the afterMigrate file and the user edits are compatible now. I spoke with Rebecca and the text got changed to 

`You are reminded of Code requirement for the mine manager to develop, and file with the Chief Inspector of Mines, a Mine Emergency Response Plan (MERP), which shall be kept up to date and followed in the event of an emergency. The MERP must be filed as a Code Required Report under Part 3.7.1 prior to start of work (Part 6.2.1), via MineSpace (https://minespace.gov.bc.ca/).`

**Review by taraepp — APPROVED** [review]
LGTM

**Review by henryoforeh-dev — APPROVED** [review]

**Pull request merged**
