### PR TITLE
MDS-1999 Composite Keycloak Roles

### PR DESCRIPTION
**Pull request by pdittaro**

### CODE REVIEW

**Comment by mmumby** [comment]
Excited to see this get merged in! When do you think it will be ready for testing?

**Comment by pdittaro** [comment]
@mmumby  This is in a state where we can start testing - Jon has been working on the active PR. I need to do a bit of work in Prod keycloak before we merge into develop - I'll hop on that tomorrow. 

I'll try and give an overview tomorrow of the Roles in keycloak as well, but the long and short of it is that we should generally try to use the 'core' prefixed roles for assigning permissions in the app (FE and BE).

**Comment by pdittaro** [comment]
Putting this back into WIP, since we've identified some conflicts that'll need to get addressed.

**Comment by thegentlemanphysicist** [comment]
A few issues I noticed.

- The Add/Edit button is still being conditionally rendered.  I believe Meredith made a pr that fixed this so chatting with her for details is best.  Questions to ask: do major and regional mines still have different work flows (they used to).  This button affect subscriptions as well as verifying data, and marking data as needing verification.
- Chief inspector role cannot upload a file to a variance.
-Administrative user cannot edit a permittee contact tile (not sure if they are supposed to)
-Administrative user Can only edit major mines due to the Add/Edit button rendered for major and not regional mines. (see first bullet point)
- The 'major mines permitting' role 
-- cannot upload docs to permits
-- cannot add contacts
-- cannot edit the contact tiles' information

**Comment by pdittaro** [comment]
Reminder that we also need to make sure that the 'minespace-proponent' role is being handled correctly.

**Comment by pdittaro** [comment]
From your issues @thegentlemanphysicist :

- The Add/Edit button is now not being conditionally rendered. 
- The Major mines should currently have the same permission as regional mines. The lack of ability to edit might be just on the major mines themselves?
- Following up on the other issues

**Comment by pdittaro** [comment]
Administrator can edit contact tile under the 'Contacts' section, not on the summary

**Comment by pdittaro** [comment]
Should be able to upload documents now, the 'document_manager' resource was too restrictive.

**Comment by pdittaro** [comment]
Reopening to clear state.

**Comment by NWCalvank** [comment]
Possible regression with local keycloak. When I run the `make keycloak-user` command(s), I get this output:
```
+
++ Creating local admin user...
+
Logging into http://localhost:8080/auth as user admin of realm master
Role not found for name: core_admin
make: *** [keycloak-user] Error 1
```

Since I'm not currently set up for local keycloak, I am still able to use the app just fine after building. Someone using local keycloak may run into problems, though.

**Comment by FreshGyan** [comment]
@NWCalvank @pdittaro We may need to postpone this post hackathon unless we can fix the local keycloak as well with this PR.
I'm not certain people during hackathon will all have IDIR's and we need to support that in any way we can

**Comment by pdittaro** [comment]
@NWCalvank @FreshGyan , I've started a seperate branch for this fix as well as the export of the keycloak configurations from Test and Prod.  https://github.com/bcgov/mds/tree/fix/keycloak-make-new-permissions 

I'd like to get this PR in seperately if possible before the end of this sprint.

**Pull request merged**
