### PR TITLE
[MDS-5383] Core: Webpack cpu and build speed improvements

### PR DESCRIPTION
**Pull request by simensma-fresh**
## Objective 
Various improvements to reduce the sustained CPU usage when running core-web locally. The improvements fall into the following buckets:

- Upgraded webpack and other build tools to their latest versions
- Increased the poll interval for file change watchers
- Switched from babel to esbuild
- Switched to webpack filesystem cache that should reduce subsequent build times a bit

[MDS-5383](https://bcmines.atlassian.net/browse/MDS-5383)

**Before:**

image
image

**After:**

image
image

TODO:
- [ ] Apply the same changes for Minespace and common package
- [ ] Test on windows and in codespaces

### CODE REVIEW

**Review by henryoforeh-dev — DISMISSED** [review]
Excellent work! This is a major breakthrough for the team. Looks like a build failure happened within the unit test github workflow.

**Review by matbusby-fw — DISMISSED** [review]
Nice!  Too bad Vite was giving you trouble, but those improvements still seem massive!

**Review by asinn134 — DISMISSED** [review]
Nice!

**Review by henryoforeh-dev — DISMISSED** [review]

**Review by henryoforeh-dev — DISMISSED** [review]
This is great work, thanks for this.

**Review by asinn134 — DISMISSED** [review]

**Review by henryoforeh-dev — DISMISSED** [review]
Nice!

**Review by henryoforeh-dev — APPROVED** [review]

**Review by asinn134 — APPROVED** [review]

**Comment by simensma-fresh** [comment]
Closing in favor of https://github.com/bcgov/mds/pull/2600

**Pull request closed without merging**
