### PR TITLE
Bond/add ses to view

### PR DESCRIPTION
**Pull request by Jsyro**
Flyway doesn't have access to foreign schema until after first run.
instead of direct access, staging table was built and is used in union on bond_view (used in aggregation in Metabase). 
refresh job is run nightly. 
Table is created in a sequential migration for view creation.

### CODE REVIEW

**Comment by pdittaro** [comment]
Does this solve the issue posited in your description?

**Review by exzizt — DISMISSED** [review]
✔️ ✔️ ✔️

**Comment by Jsyro** [comment]
@pdittaro Now it does, needed to add a sequential migration as well.

**Review by pdittaro — APPROVED** [review]
unnamed

**Pull request merged**
