### PR TITLE
adding architecture diagram

### PR DESCRIPTION
**Pull request by itchison**
Feedback from Gary and Julian to add this file to a documentation folder.

### CODE REVIEW

**Comment by pdittaro** [comment]
Should this updated on the usage.md as well?

**Comment by itchison** [comment]
> Should there also be a png attached with this on the README?

Updated

**Comment by itchison** [comment]
> Should this updated on the usage.md as well?

Updated.

**Comment by pdittaro** [comment]
Looks great, thanks for creating the docs folder.

**Pull request merged**
